### ISSUE TITLE
Idk where to ask questions but this is the only one here.

### ISSUE THREAD

**Issue by ghost** [supergvg/MAtmos#1]
Where is Presence Footsteps?
I have been searching all over the internet! And couldn't find anything. But that stupid minecraft dl website who sends viruses to you for downloading mods!!

**Comment by Brottweiler** [comment]
For 1.11 (not updated yet), look here: https://github.com/supergvg/Presence-Footsteps

For 1.10 and older, look here https://github.com/Sollace/Presence-Footsteps

For even older, look here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290546-presence-footsteps-an-overly-complicated-sound

**Comment by ghost** [comment]
Thanks, and WOW you are the most active one in the matmos pages!
