### ISSUE TITLE
1.11.2???

### ISSUE THREAD

**Issue by ghost** [supergvg/MAtmos#5]
How do I update the mod to that version??

**Comment by ghost** [comment]
Bump, bumpity bump bump.

**Comment by GVG** [comment]
Hello. Unfortunately we don't have time for Minecraft currently.

**Comment by ghost** [comment]
Oh.

**Comment by FireController1847** [comment]
@GVG Hey, how about now? I don't believe there was a huge difference between v1.11.0 and v1.11.2 (considering I'm a mod maker myself), but I have yet to update my mods to these versions anyways so who knows. Seriously, I love this mod so much and ever since Tekkit it's been my pride and joy. I can't live without this mod <3

**Comment by GVG** [comment]
Hi @FireController1847 ! There should be no difference in API between 1.11.0 and 1.11.2. Also there is a big chance that mod for 1.11.0 will work under 1.11.2. If it doesn't work, all you have to do is to compile the mod with new MCP mappings. This worked for some earlier versions.
We will take a look at it this week and will update if possible.

**Comment by averycoolbean** [comment]
@GVG Guess it didn't work since its November and there is still no 1.11.2

or you just forgot about it ._.

**Comment by GVG** [comment]
Unfortunately currently we don't have time for Minecraft. You can pull/fork this repo and simply compile the mod with 1.11.2 mappings.

**Comment by FireController1847** [comment]
You see, I'd love to update this mod manually and take on the task for you, but I don't have ANY idea how to code using LiteLoader. If this was a pure forge mod maybe, but since it's a litemod I'm out 😢

**Comment by averycoolbean** [comment]
me too i've tried but there is either not enough or outdated documentation for liteloader
